title: KubeDesk
description: Native Kubernetes Desktop App for Windows, macOS, and Linux
url: "https://akkezi.github.io"
baseurl: "/KubeDesk-Site"
theme: jekyll-theme-prime
plugins:
  - jekyll-seo-tag
